export const fakeData = {
  patients: [
    { 
      id: 1,
      name: 'michael',
      familyEmail: '1@g.co',
      code: 1328,
      status: 'procedure',
     },
     {
      id: 2,
      name: 'john',
      familyEmail: 'j@g.co',
      code: 9999,
      status: 'recovery',
     },
     {
      id: 3,
      name: 'billy',
      familyEmail: 'b@g.co',
      code: 1111,
      status: 'recovery',
     },
     {
      id: 4,
      name: 'jess',
      familyEmail: 'jess@g.co',
      code: 2222,
      status: 'recovery',
     },
     {
      id: 5,
      name: 'ryan',
      familyEmail: 'r@g.co',
      code: 3333,
      status: 'recovery',
     },
     {
      id: 6,
      name: 'steve',
      familyEmail: 'steve@g.co',
      code: 4444,
      status: 'recovery',
     },
     {
      id: 7,
      name: 'jason',
      familyEmail: 'jason@g.co',
      code: 5555,
      status: 'recovery',
     },
     {
      id: 8,
      name: 'ariel',
      familyEmail: 'ariel@g.co',
      code: 6666,
      status: 'recovery',
     },
     {
      id: 9,
      name: 'steve',
      familyEmail: 'steve@g.co',
      code: 4444,
      status: 'recovery',
     },
     {
      id: 10,
      name: 'jason',
      familyEmail: 'jason@g.co',
      code: 5555,
      status: 'recovery',
     },
     {
      id: 11,
      name: 'ariel',
      familyEmail: 'ariel@g.co',
      code: 6666,
      status: 'recovery',
     },
     {
      id: 12,
      name: 'steve',
      familyEmail: 'steve@g.co',
      code: 4444,
      status: 'recovery',
     },
     {
      id: 13,
      name: 'jason',
      familyEmail: 'jason@g.co',
      code: 5555,
      status: 'recovery',
     },
     {
      id: 14,
      name: 'ariel',
      familyEmail: 'ariel@g.co',
      code: 6666,
      status: 'recovery',
     },
     {
      id: 15,
      name: 'steve',
      familyEmail: 'steve@g.co',
      code: 4444,
      status: 'recovery',
     },
     {
      id: 16,
      name: 'jason',
      familyEmail: 'jason@g.co',
      code: 5555,
      status: 'recovery',
     },
     {
      id: 17,
      name: 'ariel',
      familyEmail: 'ariel@g.co',
      code: 6666,
      status: 'recovery',
     },
     {
      id: 18,
      name: 'steve',
      familyEmail: 'steve@g.co',
      code: 4444,
      status: 'recovery',
     },
     {
      id: 19,
      name: 'jason',
      familyEmail: 'jason@g.co',
      code: 5555,
      status: 'recovery',
     },
     {
      id: 20,
      name: 'ariel',
      familyEmail: 'ariel@g.co',
      code: 6666,
      status: 'recovery',
     },
     {
      id: 21,
      name: 'steve',
      familyEmail: 'steve@g.co',
      code: 4444,
      status: 'recovery',
     },
     {
      id: 22,
      name: 'jason',
      familyEmail: 'jason@g.co',
      code: 5555,
      status: 'recovery',
     },
     {
      id: 23,
      name: 'ariel',
      familyEmail: 'ariel@g.co',
      code: 6666,
      status: 'recovery',
     },
     {
      id: 24,
      name: 'steve',
      familyEmail: 'steve@g.co',
      code: 4444,
      status: 'recovery',
     },
     {
      id: 25,
      name: 'jason',
      familyEmail: 'jason@g.co',
      code: 5555,
      status: 'recovery',
     },
     {
      id: 26,
      name: 'ariel',
      familyEmail: 'ariel@g.co',
      code: 6666,
      status: 'recovery',
     },
  ]
}